"""Motor headless y extensible del nuevo juego de cartas."""

from .catalog import CardCatalog, CardCatalogReader, CardCatalogSnapshot
from .application import (
    AccessDenied,
    AuthenticatedMatchApplication,
    AuthenticationRequired,
    Capability,
    CommandRejected,
    ExternalIdentity,
    InMemoryIdentityAuthorization,
    InternalLoadFailure,
    InvalidDeck,
    InvalidExpectedVersion,
    InvalidIdentity,
    InvalidMatchId,
    MalformedCommand,
    OptionRejected,
    PublicLegalAction,
    PublicMatchView,
    PublicPlayerObservation,
    ResourceNotFound,
    WriteConflict,
)
from .content import (
    CardPresentation,
    CardPresentationCatalog,
    CardPresentationSnapshot,
    PublicCard,
    PublicCardCatalog,
    CollectionManifest,
    CollectionRegistry,
    CollectionRegistrySnapshot,
    CollectionSignatureEnvelope,
    CollectionTrustPolicy,
    PermissiveCollectionTrustPolicy,
    TrustedKey,
    load_manifest,
)
from .engine.game import EngineSemantics, GameEngine
from .persistence import dump_replay, dump_snapshot, load_snapshot, replay_from_log
from .rules import (
    DeckConstructionPolicy,
    DeckValidationIssue,
    DeckValidationResult,
    InvalidDeckConstruction,
    RuleSet,
    classic_deck_policy,
    mythic_deck_policy,
)
from .service import CommandSource, MatchService, MatchView
from .storage import InMemoryMatchStore, SQLiteMatchStore, VersionConflict

__all__ = [
    "CardCatalog",
    "CardCatalogReader",
    "CardCatalogSnapshot",
    "AccessDenied",
    "AuthenticatedMatchApplication",
    "AuthenticationRequired",
    "Capability",
    "CommandRejected",
    "ExternalIdentity",
    "InMemoryIdentityAuthorization",
    "InternalLoadFailure",
    "InvalidDeck",
    "InvalidExpectedVersion",
    "InvalidIdentity",
    "InvalidMatchId",
    "MalformedCommand",
    "OptionRejected",
    "PublicLegalAction",
    "PublicMatchView",
    "PublicPlayerObservation",
    "ResourceNotFound",
    "WriteConflict",
    "CardPresentation",
    "CardPresentationCatalog",
    "CardPresentationSnapshot",
    "PublicCard",
    "PublicCardCatalog",
    "CollectionManifest",
    "CollectionRegistry",
    "CollectionRegistrySnapshot",
    "CollectionTrustPolicy",
    "CollectionSignatureEnvelope",
    "PermissiveCollectionTrustPolicy",
    "TrustedKey",
    "GameEngine",
    "EngineSemantics",
    "InMemoryMatchStore",
    "MatchService",
    "MatchView",
    "CommandSource",
    "DeckConstructionPolicy",
    "DeckValidationIssue",
    "DeckValidationResult",
    "InvalidDeckConstruction",
    "RuleSet",
    "classic_deck_policy",
    "mythic_deck_policy",
    "SQLiteMatchStore",
    "VersionConflict",
    "dump_replay",
    "dump_snapshot",
    "load_manifest",
    "load_snapshot",
    "replay_from_log",
]
